version: '1.1'

services:
  go-app:
    container_name: go-app
    image: siddharth/restaurant-managment-go-app:1.0.0
    build: .
    environment:
       DATABASE_URL: "mongodb://siddharth:siddharth@mongo-db:27017/"
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db

  mongo-db:
    container_name: mongo-db
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=siddharth
      - MONGO_INITDB_ROOT_PASSWORD=siddharth
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongo/data
volumes:
  mongodata: {}    
    
